---
title: "제목"
format: html
---

> Reporting Date: December. 10, 2025

클러스터링 군집화
계층적 클러스터링에서 응집형과 분리형으로 나뉜다.
완전 연결 기반 상위 클러스터 구성 방법 - 점들 사이의 거리 계산.
허용치 범위 안에 있으면 묶는다.

밀도 기반 클러스터링 DBSCAN
4개이상이 포함되면 하나의 클러스터로 인정.
코어와 경계 데이터로 나뉜다.

이 방식은 차원의 저주 문제 발생 가능.
데이터의 차원이 증가 시 해당 공간의 부피가 기하급수적으로 증가하게 되고
모델을 추정을 위해

노이즈 데이터는 데이터셋이 아닌 클러스터 관점에서의 노이즈인 것이다.
코드: 어떤 결과의 차이가 있는지?

---

클러스터링 방법을 이용해서 추천방법을 활용할 수 있다.

예제: 스포티파이 - 음악 컨텐츠의 풍부. 추천의 정확도가 높다. 
카페에서의 매출 영향은 음료 뿐만 아니라 음악도 해당됨.

고려해야 될 요소
회원가입, 사용자의 인구통계학적 속성 정보
콘텐츠의 속성 정보, 이용정보, 구매정보

쉬운 - 내용 기반 추천
콘텐츠의 피처를 갖고 벡터변환-유사도 계산
알려진 선호 아이템들의 집합에 대해 내용을 분석
개념은 간단하다. 가장 쉽게 개발할 수 있는 것이다.
콜드 스타트 문제가 없음. 

중간 - 인구통계학적 추천, 
인구학적 그룹잉을 통한 방법이며 카이제곱 분석을 한다.
다만 노이즈에 약하다.

어려운 - 협력적 여과 추천(이용 정보)
여기에서는 콜드스타트 문제가 발생한다.
유사도 계산 - 예측값 계산
아이템에 내용 정보가 없어도 추천 가능
다만 고객 수가 많아질 수록 시간 소요 증가
희소성 문제 발생 가능. 다른 분야를 추천하지 않음.
롱테일 문제

아마존은 아이템 기반 협력적 추천 기법을 사용하였다.
인구통계학적으로 가로 방향으로 묶지 않고 아이템 간에 세로 방향으로 묶는다.
해당 아이템을 좋아한다면, 다른 아이템도 좋아할 확률 계산.

넥플리스는 협력 필터링 기반 알고리즘이며, 이때 최초로 나옴
베이지안 분류, 증가하에서 가설일 가능성으로 계산.
동시 발생 상관관계, 연관성 규칙의 측량 방법, 지지도, 향상도
뉴럴 네트워크

유튜브, 뉴럴렛, 벡터, 협력적 기법 혼합 사용.