---
title: "제 11장 비모수"
format: html
---

> Reporting Date: August. 5, 2024

1 . 자 료 의  입 력
추정과 검증의 정의

모집단의 가정이 잘못되었거나 없다면, 중심극한정리 개념을 사용하거나, 표본이 많다면 가능하다.
그러나 소표본에 경우에는 어떻게 해야 하는 건가?

그렇다면 빅데이터 시대에 소표본이 있을까?
측정이나 관측데이터에서는 의외로 데이터를 수집하기 쉽지 않다.
생물학적인 표본을 얻기 위해서 몇 년간 걸린다.

주로 우리가 보는 빅데이터란 SNS나 이미지와 같은 것이다. 
상당히 많은 연구 분야에서는 소표본이 매우 많다.



모수에 대해서 어떤 추정도 할 수 없는 경우, 분포 무관방법을 사용한다.
부호와 순위를 가지고 표현하므로, 직관적이고, 정규분포를 따를 때에도 효율은 크게 떨어지지 않으며
이를 벗어날 때에는 적극적으로 사용되는 방법이다.

---

1 . 자 료 의  입 력
파라메트릭(계산식)을 사용 기댓값, 추정, 가설 검정을 시도



표본이 작고, 단일 모집단에 대한 t검정
사인과 랭크 테스트 시도하기!

W+는 양의 부호를 가진 수의 합, 
E(W) 은 먼저, E(Ri) =n으로 볼 수 있으므로, 모든 랭크를 더한다고 했을 때, 
n+1/2으로 말할 수 있고, 귀무가설이 맞다면 전체 E(W) 중 E(W+) 은 절반의 양인 n (n+1) / 4로 볼 수 있다.

정규분포를 따를 땐 가능했던 그 연산(기댓값, 분산)을 여기서도 할 수 있다는 것.
E(Ri+)라는 건 귀무가설 하에 전체 Ri 중 전반이 나와야 한다.

Var(Ri+) = E(Ri+)^2 + [E(Ri+)]^2 이 공식에서 E(Ri+)은 안다.
문제는 E(Ri+)^2인데, (Ri+)^2 / 2 이와 같다.

따라서, 2(Ri+)^2 / 2 - (Ri+)^2 / 4 = (Ri+)^2 / 4가 된다.
이때, (Ri+)^2은 등차수열 공식을 사용하여, 최종적으로 n(n+1)(2n+1) / 24의 값이 나온다.

이는 정규표준화로 표현할 수 있으며, 정규화를 할 수 있다.
또한, 순수한 비모수로서 그대로 비교해도 무방.



두 개의 집단이 독립 표본

귀무가설은 두 개의 분포가 같다.
표본의 개수가 같지 않아도 됨, 표본의 개수가 더 작거나 W 통계량이 작을 때

과제로 증명하기: 기댓값과 분산 입증하기. Wx = R(i)

생존을 연장시키는 약을 생쥐에 투여
전후가 아니므로 사인(양수, 음수)이 나올 수가 없음

순위합검정에서 통계량이 음수값으로 나올 수 있는가?

전체 모집단에 분산을 모를 때, 서로 분산의 가정을 한 것


6장에서 했었던 모든 것들 비모수로 진행해보기
표본이 작다고 해서 t검정을 사용하는 것은 위험하다
분포에 대한 정규 가정이 들어가므로, 분포를 모를 때에는 비모수를 진행하는 것이 타당하다.

비모수 상당히 많이 쓰임

척도모수 

---

교제: 파이썬을 활용한 데이터 분석과 응용