---
title: "5장: 확률"
format: html
---

> Reporting Date: July. 8, 2024

통계적인 추론을 통해서도 모집단에 대한 다양한 정보를 얻을 수 있다.<br>
그 통계적 추론의 기초가 되는 확률이론에 대해 다루고자 한다.

## 1. 사건의 확률

동일 조건하에서 **한 가지 실험을 반복할 때,**<br>
전체 실험 횟수에서 그 사건이 일어나리라고 **예상되는 횟수의 비율**을 말한다. 
<br>

사건을 $A$ 라고 하면, 사건 $A$ 의 확률은 $P(A)$ 로 표시한다.

### 1-1. 표본공간 
Sample Space: Ω<br>

한 실험에서 나올 수 있는 모든 결과들의 모임.<br>
유한표본공간 ( Finite Sample Space )<br>

주사위 던지기의 표본공간

연속표본공간 ( Continuous Sample Space )

0과 1 사이의 모든 실수

## 1-2. 근원사건 
Elementary  Outcomes:  ω ₁ ,  ω ₂  … <br>

표본공간을 구성하는 개개의 결과.

주사위 던지기의 근원사건

### 1-3. 사건 
Event:  A,  B,  …<br>

표본공간의 부분집합으로, 어떤 특성을 갖는 결과들의 모임 (=근원사건들의 집합)

주사위 던지기의 사건 A, B

## 2. 확률의 법칙
위 정의로부터 확률의 특성을 유추할 수 있다.<br>

사건  A 가 일어날 확률은,   사건  A 에 속하는 근원사건이 일어날 확률의  "합" 과 같다.<br>
Ω 를 하나의 사건이라고 하면,  이 사건은 "반드시" 일어나므로 확률은   "1" 이 되어야 한다.<br>

## 3. 확률의 계산

### 3-1. 균일 확률

주사위 던지기에서, 각 숫자가 나올 확률<br>
Ω 가  k 개의 원소로 이루어져 있고, 각 근원사건이 일어날 가능성이  "동일" 하다고 가정할 때,<br>
근원사건 중 하나가 일어날 확률은  1 / k 로 주어진다.

또 사건  A 가  m 개의 근원사건으로 이루어져 있다면,<br>
사건  A 가 일어날 확률은 위와 같다.

### 3-2. 상대도수 수렴치로서의 확률

주사위를 60번 던져 10번 2가 나왔을 때, 2가 나올 확률<br>
동일한 실험  N 회를 반복할 때,   사건  A 의 상대도수는 위와 같이 표현된다.<br>

N 이 증가함에 따라 상대도수가  "일정한 값으로 수렴" 한다면,<br>
그 값으로 사건  A 가 일어날 확률  P ( A ) 를 추정한다.

## 4. 확률 법칙

여 사 건 ( Complementary  Event ): 사건  A 가 일어나지 않는 사건
합 사 건 ( Sum  Event ): 사건  A  또는  B 가 일어나는 사건
곱 사 건 ( Product  Event ): 사건  A  또는  B 가 동시에 일어나는 사건
배 반 사 건 ( Exclusive  Event ): 두 사건이 동시에 일어날 수 없는 경우

## 5. 조건부 확률 
Conditional  Probability<br>

한 사건의 결과가 다른 사건의 발생에 **영향을 미치는 확률**.

사건 B가 발생했을 때, 사건 A가 발생할 확률:

곱 사 건 의  확 률  법 칙  ( Multiplication  Rule  for  Probability )
두 사건이 동시에 발생할 확률을 계산하는 방법.
이 법칙은 두 사건이 독립적인지 여부에 따라 다르게 적용된다:

### 5-1. 표본공간의 분할 
Partition<br>

사건  A₁,  A₂,  …,  An 이 서로 배반사건이고,   Ω  =  A₁ ∪ … ∪ An 일 때,<br>
사건  A₁,  A₂,  …,  An 을  Ω 의 분할이라고 한다:

이때, 각각의 부분집합은 서로 겹치지 않는다:

예시:   주사위를 던지는 실험에서,   Ω 를 두 개의 부분집합으로 나눌 수 있다.

A₁ ​:  홀수가 나오는 경우 { 1,  3,  5 }
A₂ ​:  짝수가 나오는 경우 { 2,  4,  6 }

이 경우,   Ω 는 다음과 같이 표현된다:

### 5-2. 총확률의 법칙 
Law of Total Probability<br>

**표본공간의 분할** 개념을 사용하여 전체 확률을 계산하는 방법.

사건  A₁,  A₂, …, An 이 표본공간의 분할일 때,<br>
임의의 사건  B 의 확률  "P(B)"  는 다음과 같이 계산할 수 있다:

이를 조건부 확률 ( 종속사건 ) 을 사용하여 다시 쓰면:

예시:   사건  B 를  "주사위 눈이  4 이하인 사건" 으로 정의하면,

P(B) = P({ 1,  2,  3,  4 }) = ⅔
P(A₁)​ = P({ 1,  3,  5 }) = ½
P(A₂)​ = P({ 2,  4,  6 }) = ½

이 경우,   P ( B ) 는 다음과 같이 표현된다:

각 확률 값을 대입해보면:

### 5-3. 베이즈 정리 
Bayes' rule<br>

사건  A₁,  A₂,  …,  An 이   Ω 의 분할일 때,<br>
임의의 사건  B 에 대하여 다음 식이 성립한다:

예시:   사건  B 가 발생한 후,  사건  A₁ ​ 이 발생할 확률:

---

교제: 통계학: 파이썬을 이용한 분석